HarbourMasters/Shipwright

OTRGui/src/game/game.cpp, OTRGui/src/main.cpp
Fixed issues when dragging the window, like the window stopping its movement when moving the cursor too fast, or flickering all over the place. Also, the window position will be clamped to the area of the monitor/s to prevent it from going outside of them.
Also, setting VSync instead of target FPS prevents possible stuttering and probably increased CPU usage.
=> Improved window dragging.

libultraship/libultraship/GameSettings.cpp, libultraship/libultraship/GameSettings.h, libultraship/libultraship/SohImGuiImpl.cpp, soh/src/code/game.c, soh/src/code/z_bgcheck.c, soh/src/code/z_parameter.c, soh/src/code/z_player_lib.c, soh/src/overlays/actors/ovl_player_actor/z_player.c
This adds a "Cheats Menu" and adds the following options:
- Infinite Money
- Infinite Health
- Infinite Ammo
- Infinite Magic
- No Clip
- Climb Everything
- Moon Jump on L
- Super Tunic (combined Tunic Effects)
For clarity sake, Debug Mode is moved to Developer Tools. Every one of these cheats are self explanatory.
=> Add cheats menu and move Debug Mode to Developer Tools.

soh/src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
Fixes rupees being collected on the Title Screen
=> Fixed rupee drops from bushes during Title Screen

libultraship/libultraship/GameSettings.h, libultraship/libultraship/SDLController.cpp, libultraship/libultraship/SohImGuiImpl.cpp, soh/src/code/padmgr.c
Also makes it so the PS4/PS5 LED changes to the current tunic color.
=> Fixed PS5 gyro & Added GUI calibration button

soh/src/overlays/actors/ovl_player_actor/z_player.c
=> Fix aiming items

OTRExporter/OTRExporter/Main.cpp, OTRExporter/extract_assets.py, OTRExporter/extract_assets_old.py, OTRGui/src/game/game.cpp, OTRGui/src/impl/extractor/extractor.cpp, ZAPDTR/ZAPD/Main.cpp, ZAPDTR/ZAPD/ZFile.cpp
Additionally fixed oversight with audio files and related bug in OTRGui.
Switching to the new mode reduces extraction times from around 60 seconds to just 12.
=> Updated extract_assets.py to use new "extract directory" mode.

libultraship/libultraship/GameSettings.cpp, libultraship/libultraship/GameSettings.h, libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp, libultraship/libultraship/SohImGuiImpl.cpp, libultraship/libultraship/SohImGuiImpl.h, soh/soh.vcxproj, soh/soh.vcxproj.filters, soh/soh/Enhancements/debugger/debugSaveEditor.cpp, soh/soh/Enhancements/debugger/debugSaveEditor.h, soh/soh/Enhancements/debugger/debugger.cpp, soh/soh/Enhancements/debugger/debugger.h, soh/soh/OTRGlobals.cpp, soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c, soh/src/overlays/gamestates/ovl_file_choose/z_file_copy_erase.c, soh/src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_prompt.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
All file selection screens, including options, copy, erase, naming, and prompts are supported.  All pause screens and movement between them are supported.  
closes #26
=> Added DPad support to file selection and pause screens

libultraship/libultraship/GameSettings.cpp, libultraship/libultraship/GameSettings.h, libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp, libultraship/libultraship/SohImGuiImpl.cpp, libultraship/libultraship/SohImGuiImpl.h, soh/include/functions.h, soh/include/variables.h, soh/soh.vcxproj, soh/soh.vcxproj.filters, soh/soh/Enhancements/debugger/debugSaveEditor.cpp, soh/soh/Enhancements/debugger/debugSaveEditor.h, soh/soh/Enhancements/debugger/debugger.cpp, soh/soh/Enhancements/debugger/debugger.h, soh/soh/OTRGlobals.cpp, soh/src/buffers/heaps.c, soh/src/code/code_800EC960.c, soh/src/code/main.c, soh/src/code/z_message_PAL.c, soh/src/overlays/actors/ovl_En_Ossan/z_en_ossan.c, soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c, soh/src/overlays/gamestates/ovl_file_choose/z_file_copy_erase.c, soh/src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_prompt.c, soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Only adds support for going to and browsing the shelves.  DPad support for the text prompts is in another PR since all text prompts are handled in a single global way.
=> Added DPad support to shops

libultraship/libultraship/ResourceMgr.cpp
=> Prevent cached resource from being acquired while it is being destroyed

soh/src/code/sys_math3d.c
=> Fix cylinder-tri intersection for GCC

libultraship/libultraship/GameSettings.cpp, libultraship/libultraship/GameSettings.h, libultraship/libultraship/SohImGuiImpl.cpp, soh/src/code/z_parameter.c, soh/src/overlays/actors/ovl_player_actor/z_player.c
=> MM Bunny Hood enhancement

soh/src/overlays/actors/ovl_player_actor/z_player.c
Fixes compile errors introduced in f05d006479217efab7ff37d184b0e71fc971d58a.
=> Make develop compile

BUILDING.md, README.md
I will probably do some more cleanup. Here's a wip for now in-case anyone has ideas I didn't think of.
=> readme build instructions split

soh/src/code/graph.c
Funny on linux it show properly but windows require it
Will fix : 
https://discord.com/channels/808039310850130000/958069112091865108/967803963690852403
=> Quick fix for Title cards issues

soh/src/code/z_construct.c
Crashes maybe 1 time out of 100. Thanks @Random06457.
=> Fix random crash in z_construct

soh/src/code/z_message_PAL.c
=> Fix softlock when prompted to play songs at above 2x text speed

libultraship/libultraship/SDLController.cpp
Fixes crash with controller cvars.
=> Fix controller cvar crash

soh/src/code/z_actor.c
=> Title card offsets fix.

libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp
Fixes crashes when entering areas like the third room in Jabu-Jabu's Belly
=> Fix missing gMtxClear address for pal gc roms

libultraship/libultraship/Cvar.h, libultraship/libultraship/GameOverlay.cpp
Fixes compile errors on develop.
=> Replace remaining occurances of CVar_GetVar with CVar_Get

Jenkinsfile
=> Get rid of timeout

soh/include/functions.h
Fixes erros related to `thisx`.
=> Fix linux compilation

libultraship/libultraship/SohImGuiImpl.cpp
https://user-images.githubusercontent.com/60364512/168154239-fa072f08-f9e7-461b-b4c5-26f8dccb109d.mp4
Adding new tooltips for new menu items is as simple as `Tooltip("tooltiptexthere");` below any menu item you want a tooltip on
=> Adds tooltip function and tooltips to various ImGui menu items

soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
This PR contains additions for the German translation in hint_list.cpp.
- [soh-linux.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/4052555246.zip)
- [soh-mac.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/4052566895.zip)
- [soh-windows.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/4052587238.zip)
=> Additions for the German translation in hint_list.cpp
