- OTRGui/src/game/game.cpp
- OTRGui/src/game/game.h
- OTRGui/src/main.cpp
Closing the window with the X button will not close it immediately during the rendering of a frame, causing it to actually crash, but will set the engine in a pending state until it finishes the current frame.
> Fixed window not properly disposing raylib and OpenGL when closing.

- libultraship/libultraship/Window.cpp
This will allow the use of the `gamecontrollerdb.txt` from [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) which adds SDL mappings for many more controllers not supported by default, and, it being a text file loaded at runtime means users can add mappings for custom controllers to the text file without having to edit soh's code and rebuild.
This is separate from the button mapping in the `.ini` file and instead allows non-default controllers to be found and work properly in SDL.
However, I do have two questions.
- Should a `gamecontrollerdb.txt` be included in the soh repo and copied to the build folder as part of the build process if it doesn't already exist? (I'm not sure how to do this with a VS solution). Celeste takes this approach, it includes a …
> Load SDL controller db from file

- soh/src/code/z_player_lib.c
Fixes one of the issues here: [https://github.com/HarbourMasters/Shipwright/issues/38](https://github.com/HarbourMasters/Shipwright/issues/38)
Applies the position offset only when live Link is enabled.
> Fixed Link's sword being cut in preview in pause menu.

- ZAPDTR/ZAPD/Main.cpp
This removes all those warnings that were cluttering up the OTR builder's console output. I could also remove the `-eh` flag, but I figured it might have some other use and this seemed like the simplest way to do it.
> Remove unnecessary warnings

- libultraship/libultraship/SDLController.cpp
In the "bound diagonals to an octagonal range" code, uAxisThreshold is incorrect. The value should be 16, which is the difference between the cardinal maximum of 85 of the diagonal maximum of 69. edgex and edgey are simply making use of equations for a line.
> Replace uAxisThreshold with appropriate constant for octagon clamping

- libultraship/libultraship/Lib/Fast3D/U64/PR/ultra64/gbi.h
- libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_pc.h
- libultraship/libultraship/TextureMod.cpp
- soh/include/z64.h
- soh/src/code/z_kankyo.c
- soh/src/code/z_vr_box.c
- soh/src/code/z_vr_box_draw.c
In particular this removes the texture cache full invalidation instruction which significantly lowers the performance.
Also this should make it easier to replace skyboxes with hd textures.
> Don't copy skybox textures

- ZAPDTR/ZAPD/Globals.cpp
- soh/assets/xml/GC_NMQ_D/text/nes_message_data_static.xml
- soh/assets/xml/GC_NMQ_D/text/staff_message_data_static.xml
- soh/assets/xml/GC_NMQ_PAL_F/text/nes_message_data_static.xml
- soh/assets/xml/GC_NMQ_PAL_F/text/staff_message_data_static.xml
Credit for this PR goes to [Jack-Walker](https://github.com/HarbourMasters/Shipwright/commits?author=Jack-Walker)
This fixes a commandline extract crash. This PR is required to successfully compile after the latest commit.
> Single threaded zapd for terminal extract and fix for improper offsets in message_data_static.xml

- soh/src/overlays/actors/ovl_player_actor/z_player.c
Currently location title cards that are rendered as part of a cutscene function correctly, however, title cards that are displayed as you enter a location without a cutscene fail to appear. It seems the player file tries to ensure the vrom span of the title card isn't zero before rendering it but on SoH the addresses are zero so it fails to render even though the title card is perfectly fine.
Before:
After:
> Fix non-cutscene related title cards

- soh/src/code/z_actor.c
Oops, seems like I opened the other PR a bit too soon. The title card for the Shadow Temple isn't quite right (it displayed Spirit Temple), so this fixes it. As far as I know the other ones seem correct.
I would also like to mention though that while the title cards do work now, it seems like they render over the pause screen which seems like incorrect behavior. I suspect this may have something to do with the pause screen not using a framebuffer. I'm not sure if this PR should attempt to fix that, but I thought it was worth pointing out. I think this might also affect things other than the title cards as well.
> Fix Shadow Temple title card

- libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_opengl.cpp
This fixes issue: [https://github.com/HarbourMasters/Shipwright/issues/67](https://github.com/HarbourMasters/Shipwright/issues/67)
This happened with the Mirror Shield in the inventory screen preview. Also configured the blend function in OpenGL so it matches in both APIs.
> Fixed transparent texture making framebuffers also transparent in D3D11.

- libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp
- libultraship/libultraship/SohImGuiImpl.cpp
- libultraship/libultraship/SohImGuiImpl.h
- soh/soh.vcxproj
- soh/soh.vcxproj.filters
- soh/soh/Enhancements/debugger/debugSaveEditor.cpp
- soh/soh/Enhancements/debugger/debugSaveEditor.h
- soh/soh/Enhancements/debugger/debugger.cpp
- soh/soh/Enhancements/debugger/debugger.h
- soh/soh/OTRGlobals.cpp
This PR adds some initial save-editing capabilities, specifically a decent amount of the useful fields in `gSaveContext`. It also adjusts some of the interface in `SohImGui` to allow users of libultraship to add custom ImGui windows, the first of which is the titular Save Editor. Also needed was to add the ability for `SohImGui` to load textures from the otr file.
As an aside, I think it would be beneficial to extend the new custom window interface of `SohImGui` to include adding many more types of custom UI widgets, like checkboxes, but that is outside the scope of this PR.
> Add save editor

- soh/include/functions.h
- soh/include/variables.h
- soh/src/buffers/heaps.c
- soh/src/code/main.c
This PR makes sure the heap buffers are always aligned to 16 bytes which avoids a possible truncation in the heap implementations.
It also allocates the buffers from the heap instead of having large static arrays.
Note: Works fine with GCC, untested on MSVC
> Allocate aligned heaps

- libultraship/libultraship/GameSettings.cpp
- libultraship/libultraship/GameSettings.h
- libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp
- libultraship/libultraship/SohImGuiImpl.cpp
- libultraship/libultraship/SohImGuiImpl.h
- soh/soh.vcxproj
- soh/soh.vcxproj.filters
- soh/soh/Enhancements/debugger/debugSaveEditor.cpp
- soh/soh/Enhancements/debugger/debugSaveEditor.h
- soh/soh/Enhancements/debugger/debugger.cpp
- soh/soh/Enhancements/debugger/debugger.h
- soh/soh/OTRGlobals.cpp
- soh/src/code/code_800EC960.c
- soh/src/code/z_message_PAL.c
- soh/src/overlays/gamestates/ovl_file_choose/z_file_choose.c
- soh/src/overlays/gamestates/ovl_file_choose/z_file_copy_erase.c
- soh/src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_prompt.c
- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
The four DPad directions now mirror the four C buttons when playing ocarina notes.  I also added DPad support to all the text prompts that come up when talking to various characters like the owl.
> Added DPad support to ocarina and text prompts

- libultraship/libultraship/GameSettings.h
- libultraship/libultraship/Lib/Fast3D/gfx_direct3d11.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_direct3d_common.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_dxgi.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_opengl.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp
- libultraship/libultraship/Lib/Fast3D/gfx_pc.h
- libultraship/libultraship/Lib/Fast3D/gfx_rendering_api.h
- libultraship/libultraship/Lib/ImGui/imgui.h
- libultraship/libultraship/Lib/ImGui/imgui_widgets.cpp
- libultraship/libultraship/SohImGuiImpl.cpp
- libultraship/libultraship/SohImGuiImpl.h
- libultraship/libultraship/Window.cpp
- libultraship/libultraship/Window.h
- soh/include/functions.h
- soh/soh/GbiWrap.cpp
- soh/soh/OTRGlobals.cpp
- soh/soh/OTRGlobals.h
- soh/src/code/graph.c
- soh/src/code/z_kankyo.c
- soh/src/code/z_lights.c
This change simplifies and unifies how the framebuffers concept is implemented in the different gfx backends.
This allows SSAA, MSAA and N64 mode to be implemented by both the OpenGL and Direct3D 11 backends in the same way. The ImGUI gui has been updated accordingly.
When rendering for unscaled resolution, the OpenGL renderer now renders directly to the back buffer instead of to a texture which is then rendered to the back buffer, in order to save some performance.
The glClipControl usage is now removed and the y flipping has been moved to software. This should only result in a tiny performance decrease but will allow framebuffers to not be rendered upside-down on old hardware/drivers. It should also remove the need to use GLEW on Linux.
Another huge improvement that drastically reduces …
> Graphics backend enhancements etc.

- OTRExporter/extract_assets.py
- README.md
These changes may be somewhat controversial. However, I think from a normal user perspective it could be helpful.
How to use:
Place a baserom of any name in the `OTRExporter/` directory.
It should validate your checksum. If validation fails the program exits.
If you place multiple baseroms in the directory, it will let you choose which rom to use.
If you want to use commandline args instead of in-process user-input. Do the following:
`python3 extract_assets.py <number>` to select which rom to use. Note that if only one rom exists, the program just runs without needing any user input nor commandline argument.
I suppose this could be expanded to: \<version\>...
Also, please squash and merge this PR  to prevent extra commits. #githubIsMyEditor
> Implement todo in extract_assets.py

- OTRExporter/OTRExporter/DisplayListExporter.cpp
Fixes triggering the following assert when building without `NDEBUG`: https://github.com/HarbourMasters/Shipwright/blob/ceef4a94537a9b6fd14b5ff1b58f4605fd4c64fd/libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp#L1728
> Fix shift for G_LOADTILE

- libultraship/libultraship/Lib/Fast3D/gfx_opengl.cpp
`gfx_opengl_create_framebuffer` should return `i` instead of `fbo`. Fixes #191.
> Fix OpenGL framebuffer index

- libultraship/libultraship/GameSettings.cpp
- libultraship/libultraship/GameSettings.h
- libultraship/libultraship/SohImGuiImpl.cpp
- soh/src/code/z_parameter.c
***Let me preface this with the fact that I am absolutely not at all fluent in c/c++. I just look at examples and imitate. I have no idea what's considered good or bad practices, but what I did here works and that's all that I'm really able to evaluate.***
Recolors the bottom left rupee icon according to what wallet you currently have:
Green RGB: 200, 255, 100 (what was there by default)
Blue RGB: 100, 100, 255
Red RGB: 255, 100, 100
I know Ocarina of Time Randomizer implemented this as well as (I think) Majora's Mask, but I couldn't really figure out what RGB values that they were using for the colors. But I think for now, this is good enough. It can easily be changed later.
This can be turned on and off through the "Dynamic Wallet Icon" cvar option within `Enhancements` > `Graphics`
> Dynamic Wallet Rupee Icon Color

- libultraship/libultraship/GameSettings.cpp
- libultraship/libultraship/GameSettings.h
- libultraship/libultraship/SohImGuiImpl.cpp
- soh/src/code/z_message_PAL.c
Changes previous `Fast Text` option to `Skip Text`, and adds a new `Text Speed` slider, which can adjust the speed from original to 5x. 
https://user-images.githubusercontent.com/60364512/163676461-2bc18e07-2985-4cd5-9404-8c590f5ce869.mp4
> Changes fast text option to skip text, and makes text speed adjustable via a slider

- soh/src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.c
Fixes crash reported on the Wii U port: https://github.com/GaryOderNichts/Shipwright/issues/9
> Fix hardcoded keySegment address

- soh/include/macros.h
- soh/include/z64.h
- soh/src/code/graph.c
- soh/src/code/z_actor.c
Changing "OVERLAY_DISP" to "POLY_XLU_DISP" seem to fix and do not bring any errors 
(I did tried scene one by one and walked around in game) 
It may be no correct but it could point to the right direction if that is not correct.
> Potential fix for Title being over Kaleido.

- soh/src/code/z_map_exp.c
Thanks to Rozelette for this method !
> Fix minimap update in dungeon

- libultraship/libultraship/SohImGuiImpl.cpp
Was missing a way to enable outside of the .ini, so thought I'd add it here.
> Adds checkbox for visual Stone of Agony

- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
I know that not used yet but this trigger me during my tests.
so here a little fix for German and French 
It fix Zone name in current position box for both German & French languages.
Here that [Village Cocorico] that fixed :)
> Fix languages Zone name on Kaleido

- libultraship/libultraship/ConfigFile.cpp
- soh/src/code/z_message_PAL.c
Adds default setting for `text_speed` in config file, fixing a bug where if you didn't manually change it in the enhancements menu, text wouldn't progress ingame.
> Fixes default text speed

- libultraship/libultraship/SohImGuiImpl.cpp
> Makes text speed slider consistent with the rest of the UI

- soh/src/code/z_message_PAL.c
Fixes #210 
Second `textdrawpos` wasn't necessary, as whenever it's called, text appears instantly anyway, however when it's called in shops caused a visual bug where the arrow would be a square rather than an arrow.
Before fix:
After fix:
> Fixes visual bug in shops when above 2x text speed

- soh/src/code/z_message_PAL.c
rink discovered this fix for #190 in the Discord a few days ago. I suggested they PR it but haven't had a response, so I figured I'd just do it rather than let the fix languish.
Rather than just removing it, I commented it as the same code is basically duplicated for normal (non-credits) messages, and it's commented out in the other version.
> Credits message order fix

- soh/src/code/z_message_PAL.c
Reverts HarbourMasters/Shipwright#205
These need to be merged into `develop`, not `master`.
> Revert "Credits message order fix"

- OTRExporter/OTRExporter/DisplayListExporter.cpp
`gsDPSetTextureImage` does `(width)-1`, so this should be `width + 1` to maintain the correct width.
Fixes triggering the following assert when building without `NDEBUG`: https://github.com/HarbourMasters/Shipwright/blob/ceef4a94537a9b6fd14b5ff1b58f4605fd4c64fd/libultraship/libultraship/Lib/Fast3D/gfx_pc.cpp#L652
> Fix texture width for G_SETTIMG

- soh/src/code/z_message_PAL.c
Same as #205, but targeting the `develop` branch instead of `master`.
```
rink discovered this fix for https://github.com/HarbourMasters/Shipwright/issues/190 in the Discord a few days ago. I suggested they PR it but haven't had a response, so I figured I'd just do it rather than let the fix languish.
Rather than just removing it, I commented it as the same code is basically duplicated for normal (non-credits) messages, and it's commented out in the other version.
```
> Credits message order fix by rink

- soh/src/code/z_actor.c
Removing textureLanguageOffset does fix the French and German title card name that was showing as corrupted in game.
There gSaveContext.language will return 0 for English language
``textureLanguageOffset = width * height * gSaveContext.language;``
French & German will return 1 and 2 breaking the offset logic since both German and French need to be on the same offset than English
Since we need it to be zero just removing that offset make it working just fine.
My test goes as far as :
Launching game in each language see it work, walk to other scene and see if it change the title to correct one
Changing language without restarting and change scene
all of that work just fine 
Only if you change the language on runtime when the title card is draw it will not refresh. but that definitely normal …
> Fix Title card name for FRA and GER

- soh/include/macros.h
- soh/include/z64.h
- soh/src/code/graph.c
- soh/src/code/z_actor.c
- soh/src/code/z_player_lib.c
Fixes the hookshot reticle so that it will render under the pause menu but over any environmental effects, also fixes the reticle rendering with a garbage billboard matrix on the pause screen. Depends on #214.
Given that this PR moves the hookshot reticle to `TITLE_CARD_DISP` and that there may be more things that may need to move here to correctly replicate the behavior of the pause screen rendering on N64, it may be a good idea to rename this to something else. Personally my vote is for `WORLD_OVERLAY_DISP`. (Specifically for things that should be rendered as an overlay over the game world and effects but under the pause screen).
> Fix hookshot reticle

- libultraship/libultraship/GameSettings.cpp
- libultraship/libultraship/GameSettings.h
- libultraship/libultraship/SDLController.cpp
- libultraship/libultraship/SohImGuiImpl.cpp
- libultraship/libultraship/SohImGuiImpl.h
- soh/soh/Enhancements/debugconsole.cpp
- soh/soh/Enhancements/debugconsole.h
- soh/soh/OTRGlobals.cpp
- soh/src/code/z_player_lib.c
Most of the parameters in the `GameSettings` class, used for enhancements and cheats, are not needed. Currently we have two parameters stored for each setting - the variable in the `GameSettings` class, and the console variable that the game logic ultimately checks for. We only need the latter. I removed this extra data in the `GameSettings` class and had it directly read/write CVars.
I also simplified the code a bit by creating a new set of functions - `EnhancementCheckbox`, `EnhancementSliderInt`, and `EnhancementSliderFloat`. Most of the items on the menu bar followed an identical pattern, and these three functions reduce what would be 4-5 lines for each menu item to just one.
> Removed redundant parameters in GameSettings.

- soh/include/functions.h
- soh/soh.vcxproj
- soh/soh.vcxproj.filters
- soh/soh/Enhancements/debugger/ImGuiHelpers.cpp
- soh/soh/Enhancements/debugger/ImGuiHelpers.h
- soh/soh/Enhancements/debugger/colViewer.cpp
- soh/soh/Enhancements/debugger/colViewer.h
- soh/soh/Enhancements/debugger/debugSaveEditor.cpp
- soh/soh/Enhancements/debugger/debugger.cpp
- soh/soh/Enhancements/debugger/debugger.h
- soh/src/code/graph.c
- soh/src/code/z_play.c
This PR adds a collision viewer. There are several collision categories: scene, bg actors, col check, and waterboxes. Each can be set as solid or transparent, and all colors are customizable. The design follows very closely with how it is in gz.
> Add Collision Viewer

- libultraship/libultraship/SohImGuiImpl.cpp
- soh/src/code/z_map_exp.c
This PR add Fixes submenu to include L&R Kaleido button color and this Dungeon icon on minimap. (under Enhancements menu)
It fixes the Dungeon Entrance icon that was not visible when it should be and was present when it should not.
Also it add the ability to show the dungeon entrance before finishing a dungeon.
This code also rework a bit the icon draw to make it a bit more readable.
Screen before fixes:
Screenshots after fixes:
Here what the fix look next to GCN version
> Fix dungeon entrance icon + feature

- soh/include/functions.h
- soh/include/z64.h
- soh/src/code/z_actor.c
- soh/src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
- soh/src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
- soh/src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
- soh/src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
- soh/src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
- soh/src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
- soh/src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
- soh/src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
- soh/src/overlays/actors/ovl_Boss_Va/z_boss_va.c
- soh/src/overlays/actors/ovl_En_fHG/z_en_fhg.c
First, Ganondorf I hate you why do you have to play bad like that?
This PR is to fix Germand and French title cards translation 
(except Ganondorf, for some reasons this one do not have translation.)
Every bosses has been tested and quite a lot of zone name.
now when you use TitleCard_InitBossName you can tell if there is a translation or not.
This need method I think that a clean one. :)
Btw in TitleCard_InitBossName() in bosses files I use true/false for better readability and in code it translate to 0/1
so that fine :)
> Bosses title cards fixes

- soh/src/code/z_actor.c
Baou is a noob and confirming it everyday.
but seriously 
This one remove uneeded line (moved it before a check)
changed bool == 1 to nada thanks Random that actually better.
changed the variable shiftBottomY where it should have been shiftTopY .-.
My bad to affected users I am sorry
> Title card fixes (actually this time)

- soh/soh/Enhancements/debugger/debugSaveEditor.cpp
Included more variables in `gSaveContext` for informational purposes including:
- fixed filename display and (rudimentary) editor
- Entrance and cutscene indices
- Navi timer, race and trade timers
- Audio and Z-Target options
- Mini-game high scores
- More flags, including: `eventChkInf`, `itemGetInf`, `eventInf`, and `infTable`
- Player-specific variables, such as Link's position, rotation, model rotation, velocities, etc
- A way to change current equips (rough draft for now, wasn't able to make it nice like in the inventory tab)
As always, feedback is appreciated!
> Save Editor Enhancements

- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
This fix the map name show in Kaleido menu when using German or French language.
> Fix actual position maps name GER/FRA

- soh/src/code/z_player_lib.c
`sTemp` goes out of scope after the closing curly bracket
> Fix tunic colors

- soh/src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c
This fix the name of the dungeon not being translated in pause menu -> map.
as seen here : 
Now it properly show this :
> Fix Dungeons maps name GER/FRA in Kaleido

- libultraship/libultraship/Cvar.cpp
- libultraship/libultraship/Cvar.h
- libultraship/libultraship/SohConsole.cpp
- soh/soh/Enhancements/debugconsole.cpp
Avoid constructing a new string every time a `CVar` is accessed, make string values in the `CVar` structure `const`, use `std::unique_ptr` for `CVar` instead of raw pointers with `new`, remove `CVar_GetVar` and just use `CVar_Get` (I didn't see a reason to have both).
> Improve CVars a bit

- Jenkinsfile
30min could possibly be too low in some instances
> Increase build pipeline timeout

- libultraship/libultraship/ConfigFile.cpp
This changes the default backend to an empty string, which means dx11 on Windows.
Why (compared to SDL+OpenGL)?
- Imgui can create windows outside the main window.
- Better performance, i.e. less CPU% and GPU% usage. At least on my laptop with Intel / Nvidia optimus.
- Less and consistent input lag (up to 16.6 ms less on a 60 Hz monitor). This is due to DXGI gives better vsync capabilities to actually wait until the previous frame has been processed by the DWM or has been flipped if full screen. With OpenGL we can only guess when the vsync happens, which could be totally off (or we can push frames in a queue and let the video driver block at an arbitrary point, which usually leads to high input lag).
Other than that, the DXGI/DX11 backend should by now have the same features as …
> Use DX11 by default, if available

- soh/assets/xml/GC_NMQ_D/textures/map_48x85_static.xml
- soh/assets/xml/GC_NMQ_PAL_F/textures/map_48x85_static.xml
This prevents the warnings from coming up when extracting assets.
> Add new XMLs with offsets for map 45*85

- OTRGui/src/game/game.cpp
Previously said Master Quest rom would work, this removes that and replaces it with GameCube PAL.
Before:
After:
> Corrects tooltip on OTRGui

- libultraship/libultraship/SohImGuiImpl.cpp
- soh/soh/Enhancements/bootcommands.c
- soh/src/overlays/actors/ovl_player_actor/z_player.c
Nintendo messed up and used a 0 instead of a 1 which basically pulled the wrong animation to load while holding two handed items
https://user-images.githubusercontent.com/47987542/168158698-e1f1705a-7661-4f34-aaba-11620dcda502.mp4
https://user-images.githubusercontent.com/47987542/168159728-91543a81-aa89-4c2a-960e-d2f21d0b4e89.mp4
> Fixed idle animations for Two Handed Items

- soh/src/code/graph.c
Implements a workaround that closes #183 by updating the controllers 3 times as often in its current call site. Eventually the proper fix would be implementing os thread functions as laid out in #189 by Kenix and then allowing controller inputs to be read in a separate thread, but this works well enough for now from what I can see.
Edit: Alternatively I could just implement `osCreateThread` in this PR but I'm not entirely sure the proper way to implement it considering the thread parameters may need to be handled. Also would `osStartThread` and `osStopThread` need to be implemented too in that case?
> Workaround for #183

- soh/src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
This fix the issues that the Hands enemies keep splitting preventing a chest to spawn a door to open and so be softlocked.
here the fix in action :
[Direct link(I'd prefer Zelda but okay) to webm](https://baoulettes.fr/Uploads/uz5phmudo7dcs5en0tl4ojqo4.webm)
> ACTOR_EN_FLOORMAS splitting fix

- soh/src/code/z_message_PAL.c
This fix the red ocarina texts box and signs.
It should also just fix every texts boxes that miss match what they should.
I did a full run without issues.
If there is a better place to put that gSPInvalidateTexCache feel free to tell me :)
> Fix texts box color & background issues

- soh/src/code/z_parameter.c
Fix the button "Return" (Start) not being translated in Kaleido menu.
This is probably not the best way to do it but I had no any ideas how to make it more simple.
Incorrect: 
how it is (notice that Quitter?):
> Return button translation for GER/FRA

- soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp
- soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp
This PR contains the full German translation of hint_list_exclude_dungeon.cpp and hint_list_exclude_overworld.cpp combined with a small fix for the French translation.
I put emphasis on the usage of the old German orthography and the preservation of the original expressions.
- [soh.otr.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/1844964162.zip)
- [soh-linux.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/1845012945.zip)
- [soh-mac.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/1845013292.zip)
- [soh-windows.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/1845101008.zip)
> Additions for the German translation in two files

- soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
This PR contains many additions for the German translation in hint_list.cpp combined with very few additional fixes.
I put emphasis on the usage of the old German orthography and the preservation of the original expressions.
- [soh.otr.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2019083322.zip)
- [soh-mac.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2019100564.zip)
- [soh-linux.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2019103428.zip)
- [soh-windows.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2019103933.zip)
> Additions for the German translation in hint_list.cpp

- soh/soh/Enhancements/randomizer/3drando/hint_list.cpp
This PR contains some additions and fixes for the German translation as well as for the French one in hint_list.cpp.
- [soh-linux.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2368313504.zip)
- [soh-mac.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2368315010.zip)
- [soh-windows.zip](https://nightly.link/HarbourMasters/Shipwright/actions/artifacts/2368316628.zip)
> Additions and fixes for two translations in hint_list.cpp
